import type { RawMatch, RawPlayer, RawStanding, RawTeam } from './nhl.types';

export const RAW_TEAMS: RawTeam[] = [
  { id: 'ANA', city: 'Anaheim', name: 'Ducks', fullName: "Ducks d'Anaheim", tag: 'Ducks', conference: 'Western', division: 'Pacific', color: '#F47A38' },
  { id: 'BOS', city: 'Boston', name: 'Bruins', fullName: 'Bruins de Boston', tag: 'Bruins', conference: 'Eastern', division: 'Atlantic', color: '#FFB81C' },
  { id: 'BUF', city: 'Buffalo', name: 'Sabres', fullName: 'Sabres de Buffalo', tag: 'Sabres', conference: 'Eastern', division: 'Atlantic', color: '#003087' },
  { id: 'CGY', city: 'Calgary', name: 'Flames', fullName: 'Flames de Calgary', tag: 'Flames', conference: 'Western', division: 'Pacific', color: '#D2001C' },
  { id: 'CAR', city: 'Caroline', name: 'Hurricanes', fullName: 'Hurricanes de la Caroline', tag: 'Hurricanes', conference: 'Eastern', division: 'Metropolitan', color: '#CC0000' },
  { id: 'CHI', city: 'Chicago', name: 'Blackhawks', fullName: 'Blackhawks de Chicago', tag: 'Blackhawks', conference: 'Western', division: 'Central', color: '#CF0A2C' },
  { id: 'COL', city: 'Colorado', name: 'Avalanche', fullName: "Avalanche du Colorado", tag: 'Avalanche', conference: 'Western', division: 'Central', color: '#6F263D' },
  { id: 'CBJ', city: 'Columbus', name: 'Blue Jackets', fullName: 'Blue Jackets de Columbus', tag: 'BlueJackets', conference: 'Eastern', division: 'Metropolitan', color: '#002654' },
  { id: 'DAL', city: 'Dallas', name: 'Stars', fullName: 'Stars de Dallas', tag: 'Stars', conference: 'Western', division: 'Central', color: '#006847' },
  { id: 'DET', city: 'Détroit', name: 'Red Wings', fullName: 'Red Wings de Détroit', tag: 'RedWings', conference: 'Eastern', division: 'Atlantic', color: '#CE1126' },
  { id: 'EDM', city: 'Edmonton', name: 'Oilers', fullName: "Oilers d'Edmonton", tag: 'Oilers', conference: 'Western', division: 'Pacific', color: '#041E42' },
  { id: 'FLA', city: 'Floride', name: 'Panthers', fullName: 'Panthers de la Floride', tag: 'Panthers', conference: 'Eastern', division: 'Atlantic', color: '#041E42' },
  { id: 'LAK', city: 'Los Angeles', name: 'Kings', fullName: 'Kings de Los Angeles', tag: 'Kings', conference: 'Western', division: 'Pacific', color: '#111111' },
  { id: 'MIN', city: 'Minnesota', name: 'Wild', fullName: 'Wild du Minnesota', tag: 'Wild', conference: 'Western', division: 'Central', color: '#154734' },
  { id: 'MTL', city: 'Montréal', name: 'Canadiens', fullName: 'Canadiens de Montréal', tag: 'Canadiens', conference: 'Eastern', division: 'Atlantic', color: '#AF1E2D' },
  { id: 'NSH', city: 'Nashville', name: 'Predators', fullName: 'Predators de Nashville', tag: 'Predators', conference: 'Western', division: 'Central', color: '#FFB81C' },
  { id: 'NJD', city: 'New Jersey', name: 'Devils', fullName: 'Devils du New Jersey', tag: 'Devils', conference: 'Eastern', division: 'Metropolitan', color: '#CE1126' },
  { id: 'NYI', city: 'Long Island', name: 'Islanders', fullName: 'Islanders de New York', tag: 'Islanders', conference: 'Eastern', division: 'Metropolitan', color: '#00539B' },
  { id: 'NYR', city: 'New York', name: 'Rangers', fullName: 'Rangers de New York', tag: 'Rangers', conference: 'Eastern', division: 'Metropolitan', color: '#0038A8' },
  { id: 'OTT', city: 'Ottawa', name: 'Sénateurs', fullName: "Sénateurs d'Ottawa", tag: 'Senateurs', conference: 'Eastern', division: 'Atlantic', color: '#E31837' },
  { id: 'PHI', city: 'Philadelphie', name: 'Flyers', fullName: 'Flyers de Philadelphie', tag: 'Flyers', conference: 'Eastern', division: 'Metropolitan', color: '#F74902' },
  { id: 'PIT', city: 'Pittsburgh', name: 'Penguins', fullName: 'Penguins de Pittsburgh', tag: 'Penguins', conference: 'Eastern', division: 'Metropolitan', color: '#FCB514' },
  { id: 'SJS', city: 'San Jose', name: 'Sharks', fullName: 'Sharks de San Jose', tag: 'Sharks', conference: 'Western', division: 'Pacific', color: '#006D75' },
  { id: 'SEA', city: 'Seattle', name: 'Kraken', fullName: 'Kraken de Seattle', tag: 'Kraken', conference: 'Western', division: 'Pacific', color: '#001628' },
  { id: 'STL', city: 'Saint-Louis', name: 'Blues', fullName: 'Blues de Saint-Louis', tag: 'Blues', conference: 'Western', division: 'Central', color: '#002F87' },
  { id: 'TBL', city: 'Tampa', name: 'Lightning', fullName: 'Lightning de Tampa', tag: 'Lightning', conference: 'Eastern', division: 'Atlantic', color: '#002868' },
  { id: 'TOR', city: 'Toronto', name: 'Maple Leafs', fullName: 'Maple Leafs de Toronto', tag: 'MapleLeafs', conference: 'Eastern', division: 'Atlantic', color: '#00205B' },
  { id: 'UTA', city: 'Utah', name: 'Mammoth', fullName: "Mammoth de l'Utah", tag: 'Mammoth', conference: 'Western', division: 'Central', color: '#6CACE4' },
  { id: 'VAN', city: 'Vancouver', name: 'Canucks', fullName: 'Canucks de Vancouver', tag: 'Canucks', conference: 'Western', division: 'Pacific', color: '#00205B' },
  { id: 'VGK', city: 'Las Vegas', name: 'Golden Knights', fullName: 'Golden Knights de Vegas', tag: 'Vegas', conference: 'Western', division: 'Pacific', color: '#B4975A' },
  { id: 'WSH', city: 'Washington', name: 'Capitals', fullName: 'Capitals de Washington', tag: 'Capitals', conference: 'Eastern', division: 'Metropolitan', color: '#C8102E' },
  { id: 'WPG', city: 'Winnipeg', name: 'Jets', fullName: 'Jets de Winnipeg', tag: 'Jets', conference: 'Western', division: 'Central', color: '#041E42' },
];

export const RAW_PLAYERS: RawPlayer[] = [
  { id: 'mcdavid', nhlId: 8478402, first: 'Connor', last: 'McDavid', team: 'EDM', pos: 'C', no: 97, shoots: 'L', gp: 6, g: 7, a: 9, pm: 8 },
  { id: 'draisaitl', nhlId: 8477934, first: 'Leon', last: 'Draisaitl', team: 'EDM', pos: 'C', no: 29, shoots: 'L', gp: 6, g: 4, a: 8, pm: 5 },
  { id: 'mackinnon', nhlId: 8477492, first: 'Nathan', last: 'MacKinnon', team: 'COL', pos: 'C', no: 29, shoots: 'R', gp: 6, g: 6, a: 7, pm: 6 },
  { id: 'makar', nhlId: 8480069, first: 'Cale', last: 'Makar', team: 'COL', pos: 'D', no: 8, shoots: 'R', gp: 6, g: 2, a: 9, pm: 7 },
  { id: 'matthews', nhlId: 8479318, first: 'Auston', last: 'Matthews', team: 'TOR', pos: 'C', no: 34, shoots: 'L', gp: 6, g: 7, a: 3, pm: 4 },
  { id: 'nylander', nhlId: 8477939, first: 'William', last: 'Nylander', team: 'TOR', pos: 'RW', no: 88, shoots: 'R', gp: 6, g: 4, a: 5, pm: 3 },
  { id: 'crosby', nhlId: 8471675, first: 'Sidney', last: 'Crosby', team: 'PIT', pos: 'C', no: 87, shoots: 'L', gp: 6, g: 3, a: 6, pm: 2 },
  { id: 'ovechkin', nhlId: 8471214, first: 'Alex', last: 'Ovechkin', team: 'WSH', pos: 'LW', no: 8, shoots: 'R', gp: 6, g: 5, a: 2, pm: 1 },
  { id: 'bedard', nhlId: 8484145, first: 'Connor', last: 'Bedard', team: 'CHI', pos: 'C', no: 98, shoots: 'R', gp: 6, g: 4, a: 5, pm: -2 },
  { id: 'kucherov', nhlId: 8476453, first: 'Nikita', last: 'Kucherov', team: 'TBL', pos: 'RW', no: 86, shoots: 'L', gp: 6, g: 5, a: 6, pm: 4 },
  { id: 'vasilevskiy', nhlId: 8476883, first: 'Andrei', last: 'Vasilevskiy', team: 'TBL', pos: 'G', no: 88, shoots: 'L', gp: 4, g: 0, a: 0, pm: 0, w: 2, sv: 0.914, gaa: 2.64 },
  { id: 'shesterkin', nhlId: 8478048, first: 'Igor', last: 'Shesterkin', team: 'NYR', pos: 'G', no: 31, shoots: 'L', gp: 4, g: 0, a: 0, pm: 0, w: 3, sv: 0.927, gaa: 2.18 },
  { id: 'kaprizov', nhlId: 8478864, first: 'Kirill', last: 'Kaprizov', team: 'MIN', pos: 'LW', no: 97, shoots: 'L', gp: 6, g: 4, a: 4, pm: 3 },
  { id: 'jack-hughes', nhlId: 8481559, first: 'Jack', last: 'Hughes', team: 'NJD', pos: 'C', no: 86, shoots: 'L', gp: 6, g: 3, a: 7, pm: 2 },
  { id: 'quinn-hughes', nhlId: 8480800, first: 'Quinn', last: 'Hughes', team: 'VAN', pos: 'D', no: 43, shoots: 'L', gp: 6, g: 1, a: 8, pm: 4 },
  { id: 'pastrnak', nhlId: 8477956, first: 'David', last: 'Pastrnak', team: 'BOS', pos: 'RW', no: 88, shoots: 'R', gp: 6, g: 5, a: 4, pm: 3 },
  { id: 'suzuki', nhlId: 8480018, first: 'Nick', last: 'Suzuki', team: 'MTL', pos: 'C', no: 14, shoots: 'R', gp: 6, g: 3, a: 5, pm: 2 },
  { id: 'caufield', nhlId: 8481540, first: 'Cole', last: 'Caufield', team: 'MTL', pos: 'RW', no: 13, shoots: 'R', gp: 6, g: 6, a: 2, pm: 1 },
  { id: 'hutson', nhlId: 8483457, first: 'Lane', last: 'Hutson', team: 'MTL', pos: 'D', no: 48, shoots: 'L', gp: 6, g: 2, a: 6, pm: 5 },
  { id: 'brady-tkachuk', nhlId: 8480801, first: 'Brady', last: 'Tkachuk', team: 'OTT', pos: 'LW', no: 7, shoots: 'L', gp: 6, g: 3, a: 4, pm: -1 },
  { id: 'stutzle', nhlId: 8482116, first: 'Tim', last: 'Stützle', team: 'OTT', pos: 'C', no: 18, shoots: 'L', gp: 6, g: 2, a: 6, pm: 0 },
  { id: 'barkov', nhlId: 8477493, first: 'Aleksander', last: 'Barkov', team: 'FLA', pos: 'C', no: 16, shoots: 'L', gp: 6, g: 3, a: 5, pm: 4 },
  { id: 'aho', nhlId: 8478427, first: 'Sebastian', last: 'Aho', team: 'CAR', pos: 'C', no: 20, shoots: 'L', gp: 6, g: 4, a: 4, pm: 3 },
  { id: 'robertson', nhlId: 8480027, first: 'Jason', last: 'Robertson', team: 'DAL', pos: 'LW', no: 21, shoots: 'L', gp: 6, g: 5, a: 3, pm: 2 },
  { id: 'connor', nhlId: 8478398, first: 'Kyle', last: 'Connor', team: 'WPG', pos: 'LW', no: 81, shoots: 'L', gp: 6, g: 4, a: 3, pm: 1 },
  { id: 'eichel', nhlId: 8478403, first: 'Jack', last: 'Eichel', team: 'VGK', pos: 'C', no: 9, shoots: 'R', gp: 6, g: 3, a: 6, pm: 3 },
  { id: 'panarin', nhlId: 8478550, first: 'Artemi', last: 'Panarin', team: 'NYR', pos: 'LW', no: 10, shoots: 'R', gp: 6, g: 2, a: 7, pm: 2 },
  { id: 'michkov', nhlId: 8484387, first: 'Matvei', last: 'Michkov', team: 'PHI', pos: 'RW', no: 39, shoots: 'L', gp: 6, g: 4, a: 3, pm: -1 },
  { id: 'celebrini', nhlId: 8484801, first: 'Macklin', last: 'Celebrini', team: 'SJS', pos: 'C', no: 71, shoots: 'L', gp: 6, g: 3, a: 4, pm: -3 },
  { id: 'keller', nhlId: 8479343, first: 'Clayton', last: 'Keller', team: 'UTA', pos: 'RW', no: 9, shoots: 'L', gp: 6, g: 3, a: 3, pm: 0 },
  { id: 'dahlin', nhlId: 8480839, first: 'Rasmus', last: 'Dahlin', team: 'BUF', pos: 'D', no: 26, shoots: 'L', gp: 6, g: 1, a: 5, pm: -2 },
  { id: 'larkin', nhlId: 8477946, first: 'Dylan', last: 'Larkin', team: 'DET', pos: 'C', no: 71, shoots: 'L', gp: 6, g: 2, a: 4, pm: 1 },
  { id: 'fantilli', nhlId: 8484166, first: 'Adam', last: 'Fantilli', team: 'CBJ', pos: 'C', no: 19, shoots: 'L', gp: 6, g: 3, a: 2, pm: -1 },
  { id: 'horvat', nhlId: 8477500, first: 'Bo', last: 'Horvat', team: 'NYI', pos: 'C', no: 53, shoots: 'L', gp: 6, g: 2, a: 2, pm: 0 },
  { id: 'forsberg', nhlId: 8476887, first: 'Filip', last: 'Forsberg', team: 'NSH', pos: 'LW', no: 9, shoots: 'R', gp: 6, g: 3, a: 3, pm: 1 },
  { id: 'thomas', nhlId: 8480023, first: 'Robert', last: 'Thomas', team: 'STL', pos: 'RW', no: 25, shoots: 'R', gp: 6, g: 2, a: 5, pm: 2 },
  { id: 'kempe', nhlId: 8477960, first: 'Adrian', last: 'Kempe', team: 'LAK', pos: 'RW', no: 9, shoots: 'L', gp: 6, g: 4, a: 2, pm: 1 },
  { id: 'beniers', nhlId: 8482665, first: 'Matty', last: 'Beniers', team: 'SEA', pos: 'C', no: 10, shoots: 'L', gp: 6, g: 2, a: 3, pm: 0 },
  { id: 'carlsson', nhlId: 8484146, first: 'Leo', last: 'Carlsson', team: 'ANA', pos: 'C', no: 23, shoots: 'L', gp: 6, g: 2, a: 3, pm: -1 },
  { id: 'kadri', nhlId: 8475172, first: 'Nazem', last: 'Kadri', team: 'CGY', pos: 'C', no: 91, shoots: 'L', gp: 6, g: 2, a: 2, pm: -2 },
];

export const RAW_MATCHES: RawMatch[] = [
  { id: 'm-bos-buf', home: 'BOS', away: 'BUF', startOffsetMinutes: -160, homeScore: 4, awayScore: 1, venue: 'TD Garden' },
  { id: 'm-mtl-tor', home: 'MTL', away: 'TOR', startOffsetMinutes: -38, homeScore: 2, awayScore: 1, venue: 'Centre Bell' },
  { id: 'm-edm-vgk', home: 'VGK', away: 'EDM', startOffsetMinutes: 130, venue: 'T-Mobile Arena' },
  { id: 'm-col-dal', home: 'DAL', away: 'COL', startOffsetMinutes: 290, venue: 'American Airlines Center' },
  { id: 'm-nyr-car', home: 'CAR', away: 'NYR', startOffsetMinutes: -60 * 26, homeScore: 3, awayScore: 2, venue: 'PNC Arena', finishedIn: 'ot' },
  { id: 'm-wpg-min', home: 'MIN', away: 'WPG', startOffsetMinutes: -60 * 28, homeScore: 1, awayScore: 2, venue: 'Xcel Energy Center' },
  { id: 'm-fla-tbl', home: 'TBL', away: 'FLA', startOffsetMinutes: -60 * 32, homeScore: 5, awayScore: 2, venue: 'Amalie Arena' },
  { id: 'm-pit-wsh', home: 'WSH', away: 'PIT', startOffsetMinutes: 60 * 22, venue: 'Capital One Arena' },
  { id: 'm-chi-det', home: 'DET', away: 'CHI', startOffsetMinutes: 60 * 26, venue: 'Little Caesars Arena' },
  { id: 'm-van-sea', home: 'SEA', away: 'VAN', startOffsetMinutes: 60 * 30, venue: 'Climate Pledge Arena' },
  { id: 'm-lak-ana', home: 'ANA', away: 'LAK', startOffsetMinutes: 60 * 50, venue: 'Honda Center' },
  { id: 'm-ott-phi', home: 'PHI', away: 'OTT', startOffsetMinutes: 60 * 54, venue: 'Xfinity Mobile Arena' },
];

export const RAW_STANDINGS: RawStanding[] = [
  { team: 'FLA', wins: 5, losses: 1, ot: 0, diff: 8, streak: 'V3' },
  { team: 'BOS', wins: 4, losses: 1, ot: 1, diff: 6, streak: 'V1' },
  { team: 'TOR', wins: 4, losses: 2, ot: 0, diff: 5, streak: 'D1' },
  { team: 'MTL', wins: 3, losses: 2, ot: 1, diff: 2, streak: 'V2' },
  { team: 'TBL', wins: 3, losses: 2, ot: 1, diff: 1, streak: 'V1' },
  { team: 'OTT', wins: 3, losses: 3, ot: 0, diff: -1, streak: 'D1' },
  { team: 'DET', wins: 2, losses: 3, ot: 1, diff: -3, streak: 'D2' },
  { team: 'BUF', wins: 1, losses: 4, ot: 1, diff: -6, streak: 'D3' },
  { team: 'CAR', wins: 5, losses: 1, ot: 0, diff: 9, streak: 'V4' },
  { team: 'NYR', wins: 4, losses: 1, ot: 1, diff: 5, streak: 'V2' },
  { team: 'NJD', wins: 4, losses: 2, ot: 0, diff: 4, streak: 'V1' },
  { team: 'WSH', wins: 3, losses: 2, ot: 1, diff: 2, streak: 'D1' },
  { team: 'PIT', wins: 3, losses: 3, ot: 0, diff: 0, streak: 'V1' },
  { team: 'NYI', wins: 2, losses: 3, ot: 1, diff: -2, streak: 'D1' },
  { team: 'PHI', wins: 2, losses: 4, ot: 0, diff: -4, streak: 'D2' },
  { team: 'CBJ', wins: 1, losses: 4, ot: 1, diff: -7, streak: 'D1' },
  { team: 'DAL', wins: 5, losses: 1, ot: 0, diff: 7, streak: 'V2' },
  { team: 'COL', wins: 4, losses: 1, ot: 1, diff: 6, streak: 'V3' },
  { team: 'WPG', wins: 4, losses: 2, ot: 0, diff: 4, streak: 'V1' },
  { team: 'MIN', wins: 3, losses: 2, ot: 1, diff: 2, streak: 'D1' },
  { team: 'STL', wins: 3, losses: 3, ot: 0, diff: 0, streak: 'V1' },
  { team: 'NSH', wins: 2, losses: 3, ot: 1, diff: -2, streak: 'D2' },
  { team: 'UTA', wins: 2, losses: 4, ot: 0, diff: -3, streak: 'D1' },
  { team: 'CHI', wins: 1, losses: 5, ot: 0, diff: -8, streak: 'D4' },
  { team: 'EDM', wins: 5, losses: 0, ot: 1, diff: 10, streak: 'V5' },
  { team: 'VGK', wins: 4, losses: 1, ot: 1, diff: 6, streak: 'V1' },
  { team: 'VAN', wins: 4, losses: 2, ot: 0, diff: 4, streak: 'V2' },
  { team: 'LAK', wins: 3, losses: 2, ot: 1, diff: 2, streak: 'D1' },
  { team: 'SEA', wins: 3, losses: 3, ot: 0, diff: 1, streak: 'V1' },
  { team: 'CGY', wins: 2, losses: 3, ot: 1, diff: -2, streak: 'D1' },
  { team: 'ANA', wins: 2, losses: 4, ot: 0, diff: -4, streak: 'D2' },
  { team: 'SJS', wins: 1, losses: 4, ot: 1, diff: -7, streak: 'D3' },
];
