import { CURRENT_USER_ID } from '@/constants/session';
import type { AppNotification, Comment, FanUser, Like, Poll, Post } from '@/types/social';
import { minutesAgo } from '@/utils/date';

const portrait = (seed: string) =>
  `https://api.dicebear.com/9.x/notionists/png?seed=${encodeURIComponent(seed)}&backgroundColor=e7f0fa`;

const ice =
  'https://images.unsplash.com/photo-1515703407324-5f753afd8be8?auto=format&fit=crop&w=1400&q=80';
const arena =
  'https://images.unsplash.com/photo-1473976345543-9ffc928e648d?auto=format&fit=crop&w=1400&q=80';
const sticks =
  'https://images.unsplash.com/photo-1580748141549-71748dbe0bdc?auto=format&fit=crop&w=1400&q=80';

export const seedUser: FanUser = {
  id: CURRENT_USER_ID,
  firstName: 'Léa',
  lastName: 'Moreau',
  username: 'lea.moreau',
  avatarUrl: portrait('LeaMoreau'),
  favoriteTeamId: 'MTL',
  bio: 'Au Centre Bell dès que je peux. Le hockey est une langue, pas seulement un score.',
  points: 186,
};

export const seedFans: FanUser[] = [
  {
    id: 'u1',
    firstName: 'Camille',
    lastName: 'Bergeron',
    username: 'camilleb',
    avatarUrl: portrait('CamilleBergeron'),
    favoriteTeamId: 'MTL',
    bio: 'Le CH, même les soirs de semaine.',
    points: 460,
  },
  {
    id: 'u2',
    firstName: 'Alexis',
    lastName: 'Gagnon',
    username: 'alexisg',
    avatarUrl: portrait('AlexisGagnon'),
    favoriteTeamId: 'TOR',
    bio: 'Scotiabank Arena, section 315.',
    points: 310,
  },
  {
    id: 'u3',
    firstName: 'Noah',
    lastName: 'Pelletier',
    username: 'noahp',
    avatarUrl: portrait('NoahPelletier'),
    favoriteTeamId: 'EDM',
    bio: 'Je regarde McDavid comme on étudie un match.',
    points: 388,
  },
  {
    id: 'u4',
    firstName: 'Sofia',
    lastName: 'Marin',
    username: 'sofiam',
    avatarUrl: portrait('SofiaMarin'),
    favoriteTeamId: 'COL',
    bio: 'Avalanche depuis le déménagement.',
    points: 274,
  },
  {
    id: 'u5',
    firstName: 'Ethan',
    lastName: 'Roy',
    username: 'ethanr',
    avatarUrl: portrait('EthanRoy'),
    favoriteTeamId: 'BOS',
    bio: 'Le marché des transactions, c’est mon sport d’hiver.',
    points: 512,
  },
  {
    id: 'u6',
    firstName: 'Maya',
    lastName: 'Chen',
    username: 'mayac',
    avatarUrl: portrait('MayaChen'),
    favoriteTeamId: 'WPG',
    bio: 'Le hockey appartient à tout le monde, ou il n’appartient à personne.',
    points: 241,
  },
  {
    id: 'u7',
    firstName: 'Louis',
    lastName: 'Hébert',
    username: 'louish',
    avatarUrl: portrait('LouisHebert'),
    favoriteTeamId: 'CHI',
    bio: 'Chicago, la patience et Bedard.',
    points: 198,
  },
  {
    id: 'u8',
    firstName: 'Inès',
    lastName: 'Bouchard',
    username: 'inesb',
    avatarUrl: portrait('InesBouchard'),
    favoriteTeamId: 'VGK',
    bio: 'Vegas le soir, la LPHF le lendemain.',
    points: 356,
  },
];

export const seedPosts: Post[] = [
  {
    id: 'p1',
    authorId: 'u3',
    category: 'player',
    playerId: 'mcdavid',
    teamId: 'EDM',
    hashtags: ['McDavid', 'Oilers'],
    imageUrl: ice,
    createdAt: minutesAgo(48),
    body: 'McDavid n’a pas seulement repris son rythme. Il impose le sien. Neuf passes en six matchs, et Edmonton n’a même pas encore trouvé son meilleur jeu collectif.',
  },
  {
    id: 'p2',
    authorId: 'u1',
    category: 'team',
    playerId: 'hutson',
    teamId: 'MTL',
    hashtags: ['Canadiens', 'Hutson'],
    createdAt: minutesAgo(95),
    body: 'Hutson joue déjà comme si l’avantage numérique lui appartenait. Montréal n’a pas un simple espoir : il a un défenseur qui change la sortie de zone.',
  },
  {
    id: 'p3',
    authorId: 'u5',
    category: 'nhl',
    hashtags: ['TradeTalk'],
    createdAt: minutesAgo(180),
    body: 'Le marché des défenseurs droitiers va bouger avant la date limite. Trop d’équipes croient encore pouvoir attendre janvier pour réparer une brigade.',
  },
  {
    id: 'p4',
    authorId: 'u7',
    category: 'player',
    playerId: 'bedard',
    teamId: 'CHI',
    hashtags: ['Bedard'],
    imageUrl: sticks,
    createdAt: minutesAgo(240),
    body: 'Bedard attire trois joueurs à chaque entrée de zone et trouve quand même la passe. Chicago n’est pas rendu, mais le centre du projet est le bon.',
  },
  {
    id: 'p5',
    authorId: 'u6',
    category: 'player',
    playerId: 'ovechkin',
    teamId: 'WSH',
    hashtags: ['Ovechkin'],
    createdAt: minutesAgo(310),
    body: 'On parle encore d’Ovechkin comme d’un buteur de puissance. Regardez ses arrivées au filet : le timing est le même qu’à 25 ans.',
  },
  {
    id: 'p6',
    authorId: 'u2',
    category: 'society',
    hashtags: ['HockeyJeunesse'],
    createdAt: minutesAgo(400),
    body: 'Au Québec, inscrire un enfant au hockey compétitif coûte maintenant le prix d’un loyer. On ne peut pas parler de relève si seules certaines familles peuvent jouer.',
  },
  {
    id: 'p7',
    authorId: 'u8',
    category: 'society',
    hashtags: ['HockeyFeminin'],
    imageUrl: arena,
    createdAt: minutesAgo(520),
    body: 'Le hockey féminin n’a pas besoin d’être « la prochaine chose à surveiller ». Il a besoin d’un calendrier, de diffusion et de respect. La LPHF fait déjà le travail.',
  },
  {
    id: 'p8',
    authorId: 'u1',
    category: 'match',
    teamId: 'MTL',
    matchId: 'm-mtl-tor',
    hashtags: ['Canadiens', 'MapleLeafs'],
    createdAt: minutesAgo(36),
    body: 'Centre Bell électrique. Montréal mène d’un but et Suzuki est partout. Ce n’est pas juste un bon début de match, c’est une équipe qui se reconnaît.',
  },
  {
    id: 'p9',
    authorId: 'u4',
    category: 'player',
    playerId: 'makar',
    teamId: 'COL',
    hashtags: ['Makar'],
    createdAt: minutesAgo(640),
    body: 'Makar n’est pas seulement le meilleur défenseur offensif. Il efface des deux contre un sans se départir de la rondelle. Le trophée Norris se discute déjà trop tôt, et pourtant.',
  },
  {
    id: 'p10',
    authorId: 'u6',
    category: 'society',
    hashtags: ['Inclusion'],
    createdAt: minutesAgo(800),
    body: 'Les vestiaires ont changé, pas assez vite. L’inclusion n’est pas un thème de semaine. C’est qui a le droit de se sentir chez soi dans ce sport.',
  },
  {
    id: 'p11',
    authorId: CURRENT_USER_ID,
    category: 'team',
    teamId: 'MTL',
    hashtags: ['Canadiens'],
    createdAt: minutesAgo(150),
    body: 'J’ai revu les trois derniers matchs du CH sans le son. La structure à cinq est enfin lisible. Ce n’est pas spectaculaire à chaque présence, et c’est tant mieux.',
  },
  {
    id: 'p12',
    authorId: 'u2',
    category: 'player',
    playerId: 'matthews',
    teamId: 'TOR',
    hashtags: ['Matthews'],
    createdAt: minutesAgo(900),
    body: 'Matthews ne chasse pas seulement les buts. Il gagne ses mises en jeu dans les moments où le match se décide. Toronto a retrouvé son centre.',
  },
  {
    id: 'p13',
    authorId: CURRENT_USER_ID,
    category: 'society',
    hashtags: ['Equipement'],
    createdAt: minutesAgo(1100),
    body: 'Un bâton intermédiaire pour un adolescent dépasse souvent 300 $. On demande aux familles de suivre la croissance d’un enfant au prix du matériel pro.',
  },
  {
    id: 'p14',
    authorId: 'u5',
    category: 'team',
    teamId: 'BOS',
    hashtags: ['Bruins'],
    createdAt: minutesAgo(1300),
    body: 'Les Bruins n’ont plus le droit à la nostalgie. Le cinq de Pastrnak doit être protégé, pas entouré de raccords.',
  },
];

export const seedComments: Comment[] = [
  {
    id: 'c1',
    postId: 'p1',
    authorId: 'u4',
    createdAt: minutesAgo(40),
    body: 'Les chiffres sont absurdes, mais c’est surtout son jeu sans la rondelle qui a changé.',
  },
  {
    id: 'c2',
    postId: 'p1',
    authorId: CURRENT_USER_ID,
    parentId: 'c1',
    createdAt: minutesAgo(28),
    body: 'Oui. Il revient bas sans perdre la rondelle, et ça change toute la sortie.',
  },
  {
    id: 'c3',
    postId: 'p1',
    authorId: 'u5',
    createdAt: minutesAgo(22),
    body: 'MacKinnon est juste derrière, et ce n’est pas un compliment vide.',
  },
  {
    id: 'c4',
    postId: 'p2',
    authorId: 'u7',
    createdAt: minutesAgo(70),
    body: 'Hutson va forcer les autres équipes à changer leur façon de défendre l’avantage numérique.',
  },
  {
    id: 'c5',
    postId: 'p2',
    authorId: 'u1',
    createdAt: minutesAgo(60),
    body: '@lea.moreau tu vois la même chose sur la première vague ?',
  },
  {
    id: 'c6',
    postId: 'p6',
    authorId: 'u1',
    createdAt: minutesAgo(300),
    body: 'Même constat à Montréal. Le hockey de quartier disparaît tranquillement.',
  },
  {
    id: 'c7',
    postId: 'p6',
    authorId: 'u2',
    parentId: 'c6',
    createdAt: minutesAgo(250),
    body: 'Et les écoles ne compensent plus. Le coût est devenu le vrai filtre.',
  },
  {
    id: 'c8',
    postId: 'p8',
    authorId: 'u3',
    createdAt: minutesAgo(20),
    body: 'Suzuki est en train de devenir le match à lui seul.',
  },
  {
    id: 'c9',
    postId: 'p11',
    authorId: 'u6',
    createdAt: minutesAgo(80),
    body: 'La structure se voit surtout en infériorité. Montréal ne panique plus.',
  },
  {
    id: 'c10',
    postId: 'p7',
    authorId: CURRENT_USER_ID,
    createdAt: minutesAgo(200),
    body: 'La diffusion reste le vrai test cette saison. Sans ça, le respect reste un slogan.',
  },
  {
    id: 'c11',
    postId: 'p9',
    authorId: 'u3',
    createdAt: minutesAgo(500),
    body: 'Le contrôle en retraite est ridicule. Il n’a pas besoin de se presser.',
  },
  {
    id: 'c12',
    postId: 'p13',
    authorId: 'u6',
    createdAt: minutesAgo(700),
    body: 'Et ce n’est que le bâton. Ajoute les patins, la visière, les inscriptions.',
  },
];

export const seedLikes: Like[] = [
  ['p1', ['u1', 'u2', 'u4', 'u5', 'u6', 'u8', CURRENT_USER_ID]],
  ['p2', ['u2', 'u3', 'u7', 'u8', CURRENT_USER_ID]],
  ['p3', ['u2', 'u4', 'u6']],
  ['p4', ['u1', 'u3', 'u4', 'u8', CURRENT_USER_ID]],
  ['p5', ['u1', 'u5', 'u7']],
  ['p6', ['u1', 'u6', 'u8', CURRENT_USER_ID]],
  ['p7', ['u1', 'u2', 'u4', 'u6']],
  ['p8', ['u3', 'u5', 'u6', 'u7', CURRENT_USER_ID]],
  ['p9', ['u3', 'u5', 'u8']],
  ['p10', ['u1', 'u8']],
  ['p11', ['u1', 'u3', 'u4', 'u6']],
  ['p12', ['u5', 'u8']],
  ['p13', ['u1', 'u2', 'u6']],
  ['p14', ['u2', 'u4']],
  ['c1', [CURRENT_USER_ID, 'u3']],
  ['c9', [CURRENT_USER_ID]],
].flatMap(([targetId, userIds]) =>
  (userIds as string[]).map((userId) => ({
    targetType: (targetId as string).startsWith('c') ? 'comment' : 'post',
    targetId: targetId as string,
    userId,
  })),
);

export const seedPolls: Poll[] = [
  {
    id: 'qotd',
    question: 'Qui est actuellement le joueur le plus impressionnant de la NHL ?',
    options: [
      { id: 'qotd-mcdavid', label: 'Connor McDavid', votes: 428 },
      { id: 'qotd-mackinnon', label: 'Nathan MacKinnon', votes: 316 },
      { id: 'qotd-matthews', label: 'Auston Matthews', votes: 254 },
      { id: 'qotd-makar', label: 'Cale Makar', votes: 189 },
      { id: 'qotd-other', label: 'Autre', votes: 96 },
    ],
  },
  {
    id: 'poll-rivalry',
    question: 'Qui l’emporte ce soir entre Montréal et Toronto ?',
    options: [
      { id: 'poll-mtl', label: 'Canadiens', votes: 188 },
      { id: 'poll-tor', label: 'Maple Leafs', votes: 164 },
    ],
  },
];

export const seedNotifications: AppNotification[] = [
  { id: 'n1', type: 'reply', actorId: 'u6', postId: 'p11', createdAt: minutesAgo(18), read: false },
  { id: 'n2', type: 'reaction', actorId: 'u3', postId: 'p11', createdAt: minutesAgo(42), read: false },
  { id: 'n3', type: 'mention', actorId: 'u1', postId: 'p2', createdAt: minutesAgo(60), read: false },
  { id: 'n4', type: 'favorite_team', createdAt: minutesAgo(60 * 3), read: false },
  { id: 'n5', type: 'game_start', matchId: 'm-mtl-tor', createdAt: minutesAgo(50), read: true },
  { id: 'n6', type: 'game_result', matchId: 'm-bos-buf', createdAt: minutesAgo(60 * 6), read: true },
  { id: 'n7', type: 'poll', createdAt: minutesAgo(60 * 5), read: false },
];
